name: Deploy Snowpark Apps

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Snowflake CLI
        run: pip install --upgrade snowflake-cli

      - name: Verify Snowflake CLI installation
        run: snow --help  # Check if Snowflake CLI is installed

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Install Snowpark Python Package
        run: pip install snowflake-snowpark-python  # Ensure Snowpark Python is installed

      - name: Check Snowflake CLI Version
        run: snow --version  # Ensure it's the latest version

      - name: Debug Available Snowflake Commands
        run: snow --help  # List available commands to check if "snowpark" exists

      - name: Deploy Snowpark Apps
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        run: python deploy_snowpark_apps.py $GITHUB_WORKSPACE
